services:
  postgres:
    image: postgres:16
    container_name: payment-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: payment
      POSTGRES_USER: payment
      POSTGRES_PASSWORD: payment
    volumes:
      - payment_pgdata:/var/lib/postgresql/data

volumes:
  payment_pgdata:
